/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package torresjustinproject3;

/**
 *
 * @author jdt63
 */
public class Project3GUI extends javax.swing.JFrame {
    
    private Bookstore myBookstore;
    private double totalCost = 0.00;
    private double currentCost = 0.00;
    private int x = 1;
    private boolean enteredItem = false;
    private boolean enteredNumToBuy = false;
    private int numPurchases = 0;
    private int itemID = 0;
    
    /**
     * Creates new form Project3GUI
     */
    public Project3GUI() {
        
        Bookstore b = new Bookstore();

        Book book1 = new Book(1,"fahrenheit 451","ray bradbury",8,9.99);
        Book book2 = new Book(2, "1984","george orwell",5,15.99);
        Book book3 = new Book(3, "to kill a mockingbird","harper lee",12,12.99);
        Book book4 = new Book(4, "beloved","toni morrison",4,13.5);
        Book book5 = new Book(5, "the little prince","antoine de saint exupéry",10,7);
        Book book6 = new Book(6, "brave new world","aldous huxley",15,19);
        Book book7 = new Book(7, "charlotte's web","e.b. white",10,8.99);
        CD CD1 = new CD(8, "a night at the opera","queen",14,6.99);
        CD CD2 = new CD(9, "cuz I love you","lizzo",8,7.99);
        CD CD3 = new CD(10, "a hard day's night","the beatles",3,3.99);
        DVD DVD1 = new DVD(11, "the dark knight","n/a",5,12.99);
        DVD DVD2 = new DVD(12, "jurassic park","n/a" ,7,7.99);
        
        b.addBook(book1);
        b.addBook(book2);
        b.addBook(book3);
        b.addBook(book4);
        b.addBook(book5);
        b.addBook(book6);
        b.addBook(book7);
        b.addCD(CD1);
        b.addCD(CD2);
        b.addCD(CD3);
        b.addDVD(DVD1);
        b.addDVD(DVD2);
        
       
        
        initComponents();
        
        costLabel.setText("Total Cost: " + totalCost);
        inventoryLabel1.setText("ID: " + book1.index + " Title: " + book1.currentName + " Author: " + book1.author + " Stock: " + book1.numInInventory + " Price: " + book1.getCurrentPrice());
        inventoryLabel2.setText("ID: " + book2.index + " Title: " + book2.currentName + " Author: " + book2.author + " Stock: " + book2.numInInventory + " Price: " + book2.getCurrentPrice());
        inventoryLabel3.setText("ID: " + book3.index + " Title: " + book3.currentName + " Author: " + book3.author + " Stock: " + book3.numInInventory + " Price: " + book3.getCurrentPrice());
        inventoryLabel4.setText("ID: " + book4.index + " Title: " + book4.currentName + " Author: " + book4.author + " Stock: " + book4.numInInventory + " Price: " + book4.getCurrentPrice());
        inventoryLabel5.setText("ID: " + book5.index + " Title: " + book5.currentName + " Author: " + book5.author + " Stock: " + book5.numInInventory + " Price: " + book5.getCurrentPrice());
        inventoryLabel6.setText("ID: " + book6.index + " Title: " + book6.currentName + " Author: " + book6.author + " Stock: " + book6.numInInventory + " Price: " + book6.getCurrentPrice());
        inventoryLabel7.setText("ID: " + book7.index + " Title: " + book7.currentName + " Author: " + book7.author + " Stock: " + book7.numInInventory + " Price: " + book7.getCurrentPrice());
        inventoryLabel8.setText("ID: " + CD1.index + " Title: " + CD1.currentName + " Author: " + CD1.author + " Stock: " + CD1.numInInventory + " Price: " + CD1.getCurrentPrice());
        inventoryLabel9.setText("ID: " + CD2.index + " Title: " + CD2.currentName + " Author: " + CD2.author + " Stock: " + CD2.numInInventory + " Price: " + CD2.getCurrentPrice());
        inventoryLabel10.setText("ID: " + CD3.index + " Title: " + CD3.currentName + " Author: " + CD3.author + " Stock: " + CD3.numInInventory + " Price: " + CD3.getCurrentPrice());
        inventoryLabel11.setText("ID: " + DVD1.index + " Title: " + DVD1.currentName + " Author: " + DVD1.author + " Stock: " + DVD1.numInInventory + " Price: " + DVD1.getCurrentPrice());
        inventoryLabel12.setText("ID: " + DVD2.index + " Title: " + DVD2.currentName + " Author: " + DVD2.author + " Stock: " + DVD2.numInInventory + " Price: " + DVD2.getCurrentPrice());
        
    }
    
    Project3GUI(Bookstore mybookstore){
           this.myBookstore = myBookstore;
           
     initComponents();   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Heading = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        inventoryLabel = new javax.swing.JLabel();
        inventoryLabel1 = new javax.swing.JLabel();
        inventoryLabel2 = new javax.swing.JLabel();
        inventoryLabel3 = new javax.swing.JLabel();
        inventoryLabel4 = new javax.swing.JLabel();
        inventoryLabel5 = new javax.swing.JLabel();
        inventoryLabel6 = new javax.swing.JLabel();
        inventoryLabel7 = new javax.swing.JLabel();
        inventoryLabel8 = new javax.swing.JLabel();
        inventoryLabel9 = new javax.swing.JLabel();
        inventoryLabel10 = new javax.swing.JLabel();
        inventoryLabel11 = new javax.swing.JLabel();
        inventoryLabel12 = new javax.swing.JLabel();
        productLabel = new javax.swing.JLabel();
        productLabel1 = new javax.swing.JLabel();
        purchaseButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        idSpinner = new javax.swing.JSpinner();
        quantitySpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Heading.setFont(new java.awt.Font("Centaur", 0, 48)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("Bookstore");
        Heading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        costLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        costLabel.setText("Total Cost: $0.00");

        inventoryLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inventoryLabel.setText("Inventory");

        inventoryLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inventoryLabel1.setText("Inventory");

        inventoryLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inventoryLabel2.setText("Inventory");

        inventoryLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inventoryLabel3.setText("Inventory");

        inventoryLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inventoryLabel4.setText("Inventory");

        inventoryLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inventoryLabel5.setText("Inventory");

        inventoryLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inventoryLabel6.setText("Inventory");

        inventoryLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inventoryLabel7.setText("Inventory");

        inventoryLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inventoryLabel8.setText("Inventory");

        inventoryLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inventoryLabel9.setText("Inventory");

        inventoryLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inventoryLabel10.setText("Inventory");

        inventoryLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inventoryLabel11.setText("Inventory");

        inventoryLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inventoryLabel12.setText("Inventory");

        productLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productLabel.setText("Enter the ID of the item you wish to purchase here:");

        productLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productLabel1.setText("Enter the quantity of the item you wish to purchase here:");

        purchaseButton.setText("BUY");
        purchaseButton.setEnabled(false);
        purchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseButtonActionPerformed(evt);
            }
        });

        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        idSpinner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idSpinnerMouseClicked(evt);
            }
        });
        idSpinner.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                idSpinnerPropertyChange(evt);
            }
        });

        quantitySpinner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quantitySpinnerMouseClicked(evt);
            }
        });
        quantitySpinner.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                quantitySpinnerPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(inventoryLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(costLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(inventoryLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                .addComponent(inventoryLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inventoryLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inventoryLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inventoryLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inventoryLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inventoryLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inventoryLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inventoryLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inventoryLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inventoryLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inventoryLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(productLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(productLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 8, Short.MAX_VALUE)
                                .addComponent(exitButton)
                                .addGap(437, 437, 437)
                                .addComponent(purchaseButton)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventoryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryLabel12)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productLabel1)
                    .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchaseButton)
                    .addComponent(exitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void purchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseButtonActionPerformed
        // TODO add your handling code here:
        itemID = (int)idSpinner.getValue();
        numPurchases = (int)quantitySpinner.getValue();
        
        if(itemID == 1) {
        currentCost = 9.99;    
        } else if(itemID == 2) {
        currentCost = 15.99;   
        } else if(itemID == 3) {
        currentCost = 12.99;   
        } else if(itemID == 4) {
        currentCost = 13.5;   
        } else if(itemID == 5) {
        currentCost = 7;   
        } else if(itemID == 6) {
        currentCost = 19;   
        } else if(itemID == 7) {
        currentCost = 8.99;   
        } else if(itemID == 8) {
        currentCost = 6.99;   
        } else if(itemID == 9) {
        currentCost = 7.99;   
        } else if(itemID == 10) {
        currentCost = 3.99;   
        } else if(itemID == 11) {
        currentCost = 12.99;   
        } else if(itemID == 12) {
        currentCost = 7.99;   
        } else{
         currentCost = 0;   
        }
        
        totalCost = totalCost + currentCost * numPurchases;
        costLabel.setText("Total Cost: " + totalCost);
    }//GEN-LAST:event_purchaseButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void idSpinnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idSpinnerMouseClicked
        // TODO add your handling code here:
        enteredItem = true;
        if (enteredItem && enteredNumToBuy == true) {
        purchaseButton.setEnabled(true);
        }
    }//GEN-LAST:event_idSpinnerMouseClicked

    private void quantitySpinnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quantitySpinnerMouseClicked
        // TODO add your handling code here:
        enteredNumToBuy = true;
        if (enteredItem && enteredNumToBuy == true) {
        purchaseButton.setEnabled(true);
        }
    }//GEN-LAST:event_quantitySpinnerMouseClicked

    private void idSpinnerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_idSpinnerPropertyChange
        // TODO add your handling code here:
        enteredItem = true;
        if (enteredItem && enteredNumToBuy == true) {
        purchaseButton.setEnabled(true);
        }
    }//GEN-LAST:event_idSpinnerPropertyChange

    private void quantitySpinnerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_quantitySpinnerPropertyChange
        // TODO add your handling code here:
        enteredNumToBuy = true;
        if (enteredItem && enteredNumToBuy == true) {
        purchaseButton.setEnabled(true);
        }
    }//GEN-LAST:event_quantitySpinnerPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project3GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project3GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project3GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project3GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project3GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel costLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JSpinner idSpinner;
    private javax.swing.JLabel inventoryLabel;
    private javax.swing.JLabel inventoryLabel1;
    private javax.swing.JLabel inventoryLabel10;
    private javax.swing.JLabel inventoryLabel11;
    private javax.swing.JLabel inventoryLabel12;
    private javax.swing.JLabel inventoryLabel2;
    private javax.swing.JLabel inventoryLabel3;
    private javax.swing.JLabel inventoryLabel4;
    private javax.swing.JLabel inventoryLabel5;
    private javax.swing.JLabel inventoryLabel6;
    private javax.swing.JLabel inventoryLabel7;
    private javax.swing.JLabel inventoryLabel8;
    private javax.swing.JLabel inventoryLabel9;
    private javax.swing.JLabel productLabel;
    private javax.swing.JLabel productLabel1;
    private javax.swing.JButton purchaseButton;
    private javax.swing.JSpinner quantitySpinner;
    // End of variables declaration//GEN-END:variables
}
